# Generated by Django 4.2.3 on 2023-07-07 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_post_options_alter_post_views_alter_post_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='posts',
        ),
    ]
